#!/usr/bin/env python3
import glob
import random
import sys
import os

from os.path import expanduser
home = expanduser("~")

args = sys.argv[1:]

if len(args) == 0:
    args = [""]

walls = list()

for source in args:
    walls += glob.glob(home + "/images/wallpapers/" + source + "/*.*")

print(random.choice(walls))

